# Generated by Django 2.1.7 on 2019-03-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
    ]
