# Generated by Django 2.1.7 on 2019-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_remove_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(default='Name of Venue', max_length=150),
        ),
    ]
