# Generated by Django 2.1.7 on 2019-03-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='contactno',
            new_name='contact_no',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='is_active',
        ),
        migrations.AddField(
            model_name='venue',
            name='Addressline',
            field=models.CharField(default='Enter Address', max_length=150),
        ),
        migrations.AddField(
            model_name='venue',
            name='area',
            field=models.CharField(default='Enter Area', max_length=150),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default='Enter City', max_length=150),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(default='country', max_length=150),
        ),
        migrations.AddField(
            model_name='venue',
            name='pincode',
            field=models.CharField(default='Enter pincode', max_length=150),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(default='Enter state', max_length=150),
        ),
        migrations.AddField(
            model_name='venue',
            name='street',
            field=models.CharField(default='Enter Street', max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='ac',
            field=models.CharField(choices=[('ac', 'A/C'), ('non-ac', 'Non A/c')], max_length=10),
        ),
    ]
