# Generated by Django 2.1.7 on 2019-03-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_auto_20190310_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundsystem',
            name='contact_no',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact_no',
            field=models.CharField(max_length=150),
        ),
    ]
