# Generated by Django 2.1.7 on 2019-03-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_auto_20190310_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundsystem',
            name='address_id',
        ),
    ]
