# Generated by Django 2.1.7 on 2019-03-10 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Database', '0008_remove_soundsystem_address_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, max_length=150, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=150)),
                ('cost', models.CharField(max_length=150)),
                ('name', models.CharField(default='Name of Venue', max_length=150)),
                ('Addressline', models.CharField(default='Enter Address', max_length=150)),
                ('street', models.CharField(default='Enter Street', max_length=150)),
                ('area', models.CharField(default='Enter Area', max_length=150)),
                ('city', models.CharField(default='Enter City', max_length=150)),
                ('state', models.CharField(default='Enter state', max_length=150)),
                ('pincode', models.CharField(default='Enter pincode', max_length=150)),
                ('country', models.CharField(default='country', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
