# Generated by Django 2.1.7 on 2019-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_decoration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catering',
            name='address_id',
        ),
        migrations.AddField(
            model_name='catering',
            name='Addressline',
            field=models.CharField(default='Enter Address', max_length=150),
        ),
        migrations.AddField(
            model_name='catering',
            name='area',
            field=models.CharField(default='Enter Area', max_length=150),
        ),
        migrations.AddField(
            model_name='catering',
            name='city',
            field=models.CharField(default='Enter City', max_length=150),
        ),
        migrations.AddField(
            model_name='catering',
            name='country',
            field=models.CharField(default='country', max_length=150),
        ),
        migrations.AddField(
            model_name='catering',
            name='name',
            field=models.CharField(default='Name of Venue', max_length=150),
        ),
        migrations.AddField(
            model_name='catering',
            name='pincode',
            field=models.CharField(default='Enter pincode', max_length=150),
        ),
        migrations.AddField(
            model_name='catering',
            name='state',
            field=models.CharField(default='Enter state', max_length=150),
        ),
        migrations.AddField(
            model_name='catering',
            name='street',
            field=models.CharField(default='Enter Street', max_length=150),
        ),
    ]
