# Generated by Django 2.1.7 on 2019-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0010_auto_20190310_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='cost',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='Addressline',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='area',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='contact_no',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='pincode',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='state',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catering',
            name='street',
            field=models.CharField(default='', max_length=150),
        ),
    ]
