# Generated by Django 2.1.7 on 2019-02-24 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=150, primary_key=True, serialize=False)),
                ('addressline', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('expected_people', models.CharField(max_length=150)),
                ('confirmed_people', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('needprinted', models.BooleanField(default=False)),
                ('iscustomized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=150, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=150, primary_key=True, serialize=False)),
                ('capacity', models.CharField(max_length=150)),
                ('ac', models.BooleanField(default=False)),
                ('contactno', models.CharField(max_length=150, unique=True)),
                ('cost', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Address')),
            ],
        ),
    ]
