# Generated by Django 2.1.7 on 2019-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20190224_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
